//
// DocumentPropertyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DocumentPropertyRequest: Codable, JSONEncodable, Hashable {

    /** Arbitrary property that can be attached to a document. */
    public var property: AnyCodable?

    public init(property: AnyCodable?) {
        self.property = property
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case property
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(property, forKey: .property)
    }
}

